import { IConItem, IConItemDetail, ILastSaleItem } from "@/types/api";

export const menuListMockData: IConItem[] = [
  {
    id: 137,
    name: "카페아메리카노 T",
    originalPrice: 4500,
    minSellingPrice: 3760,
    imageUrl: "https://d2lfdrnysfmya6.cloudfront.net/eeddb1dc-0728-45a8-9c37-5aab2c099224.jpg",
  },
  {
    id: 3949,
    name: "[Gift] 무료 음료 쿠폰 (전 사이즈)",
    originalPrice: 7500,
    minSellingPrice: 6090,
    imageUrl: "https://d2lfdrnysfmya6.cloudfront.net/b1da383f-9872-4e38-845a-d050712d523a.jpg",
  },
  {
    id: 180,
    name: "카페라떼 T",
    originalPrice: 5000,
    minSellingPrice: 4390,
    imageUrl: "https://d2lfdrnysfmya6.cloudfront.net/d97f137f-ecda-4446-8287-9e767a58aa10.jpg",
  },
  {
    id: 3066,
    name: "부드러운 디저트 세트 (부드러운 생크림 카스텔라 + 아메리카노 T 2)",
    originalPrice: 13500,
    minSellingPrice: 11810,
    imageUrl: "https://d2lfdrnysfmya6.cloudfront.net/c97d61ce-3a16-4849-b0be-e3af096ca0a5.jpg",
  },
  {
    id: 3308,
    name: "무료음료쿠폰 Tall (추가결제시 사이즈업가능)",
    originalPrice: 6500,
    minSellingPrice: 5390,
    imageUrl: "https://d2lfdrnysfmya6.cloudfront.net/6b3bdf42-6ec3-477e-b9e5-175f4f2fc803.jpg",
  },
  {
    id: 1227,
    name: "자바 칩 프라푸치노 T",
    originalPrice: 6300,
    minSellingPrice: 5730,
    imageUrl: "https://d2lfdrnysfmya6.cloudfront.net/6dd906de-a7b7-49f8-9b56-092d1feb9274.jpg",
  },
  {
    id: 6083,
    name: "카페라떼 커플세트(카페라떼 T 2잔)",
    originalPrice: 10000,
    minSellingPrice: 8920,
    imageUrl: "https://d2lfdrnysfmya6.cloudfront.net/ed5a501a-95a7-42f4-9244-465d2b506250.jpg",
  },
  {
    id: 8137,
    name: "행복한 기운 세트(카페라떼 T2 + 슈크림 가득 바움쿠헨)",
    originalPrice: 16900,
    minSellingPrice: 14850,
    imageUrl: "https://d2lfdrnysfmya6.cloudfront.net/e991664e-0c8d-41d2-9d32-676b42939766.jpg",
  },
  {
    id: 13669,
    name: "카페 아메리카노 T 2잔 + The 촉촉 초콜릿 생크림 케이크",
    originalPrice: 14900,
    minSellingPrice: 13150,
    imageUrl: "https://d2na9jaypdrp94.cloudfront.net/BbJGb1xUhI.png",
  },
  {
    id: 2726,
    name: "기분좋은 디저트 세트(클라우드 치즈 케이크 + 아메T2)",
    originalPrice: 14500,
    minSellingPrice: 12700,
    imageUrl: "https://d2lfdrnysfmya6.cloudfront.net/71eaf908-5129-44b5-adff-8f8b5b339ccb.jpg",
  },
];

export const lastSaleListMockData: ILastSaleItem[] = [
  {
    expireAt: "2023-05-08T15:00:00.000Z",
    id: 429,
    name: "모바일금액권 1만원권",
    originalPrice: 10000,
    createdAt: "2017-02-01T04:18:18.000Z",
    sfId: "4540891300",
    minSellingPrice: 9140,
    ncSellingPrice: 9300,
    information: null,
    tip: null,
    warning: null,
    discountRate: 9,
    askingPrice: 8550,
    isRefuse: 1,
    isBlock: 0,
    info: "사용 가능 브랜드 : 롯데리아, 엔제리너스커피, 크리스피크림 도넛",
    isOnlyAccount: 0,
    conCategory2Id: 69,
    imageUrl: "https://d2na9jaypdrp94.cloudfront.net/7WOEYfImBl.png",
    descriptionImageUrl: null,
    topDescriptionImageUrl: null,
    bottomDescriptionImageUrl: null,
    tutorialImageUrl: null,
    shortcutUrl: null,
    savingRatio: 0,
    isBarcode: true,
    conCategory2: {
      id: 69,
      name: "엔제리너스커피",
      adminUserId: 10,
      priority: 7300,
      createdAt: "2017-01-26T07:23:40.000Z",
      conCategory1Id: 67,
      info: "· 금액권의 경우 별도의 등록은 불가하며, 바코드 이미지를 매장에 제시 후 이용해주셔야 합니다.",
      imageUrl: "https://d1tftw9jjs9bx5.cloudfront.net/ad6fe3a7-fe7f-4276-8db6-a1978c010b54.jpg",
      conCategory1: {
        id: 67,
        name: "카페",
        createdAt: "2017-01-26T07:13:48.000Z",
        priority: 10001,
        discountRate: 0,
        info: "·  품목형은 동일 품목으로만 교환이 가능하며 타 상품 교환,금액권처럼 사용시 사용이 불가하거나 원가금액만큼 제공 받을 수 있는건 아닙니다.\n·  일부 매장, 품목형의 경우 사용이 제한될 수 있으므로 사용 가능 여부는 방문하실 매장에 미리 확인 후 구매 부탁드립니다.\n·  구매하신 상품은 반드시 유효기간 내에 사용해 주셔야 합니다.\n· 포인트 적립 및 제휴카드 할인 등은 교환처의 정책에 따르므로 모바일 쿠폰의 경우 적립, 할인 등이 불가할 수 있습니다.\n·  바코드 인식이 불가할 경우 수기로 입력하여 사용 가능합니다. 또한 사용처의 연동 문제로 키오스크 사용이 불가 할 수 있으므로 매장 직원에게 사용시도 부탁드리겠습니다.\n·  사용처에서 제공하는 웹, 앱 등에 적용이 불가할 수 있으며 쿠폰은 선택하여 구매가 불가하므로 적용 불가 쿠폰일 경우 오프라인 매장에서 사용 시도 부탁드립니다.\n·  프로모션 및 이벤트 상품으로 구매하신 상품의 원가와 영수증에 표기되는 금액이 상이할 수 있습니다.\n· 모바일 쿠폰 중복 사용등은 사용처의 정책이므로 자세한 사항은 방문하실 매장 혹은 사용처 고객센터로 문의 후 구매 권장드립니다.",
        imageUrl: "https://d1dsr05o5i286u.cloudfront.net/a2402a35-038b-4b68-a152-2cc14dff532c.jpg",
      },
    },
  },
  {
    expireAt: "2023-05-09T15:00:00.000Z",
    id: 4956,
    name: "E-Gift Card 9만원",
    originalPrice: 90000,
    createdAt: "2019-03-14T05:35:26.000Z",
    sfId: "4358015024",
    minSellingPrice: 86390,
    ncSellingPrice: 87500,
    information: null,
    tip: null,
    warning: null,
    discountRate: 4,
    askingPrice: 81000,
    isRefuse: 1,
    isBlock: 0,
    info: "· 스타벅스 앱에서 등록 후 사용가능합니다.",
    isOnlyAccount: 0,
    conCategory2Id: 63,
    imageUrl: "https://d2lfdrnysfmya6.cloudfront.net/0800e3ce-757e-4d18-a178-5b8ed6d77dc1.jpg",
    descriptionImageUrl: null,
    topDescriptionImageUrl: null,
    bottomDescriptionImageUrl: null,
    tutorialImageUrl: null,
    shortcutUrl: null,
    savingRatio: 0,
    isBarcode: true,
    conCategory2: {
      id: 63,
      name: "스타벅스",
      adminUserId: 10,
      priority: 10000,
      createdAt: "2017-01-26T07:14:27.000Z",
      conCategory1Id: 67,
      info: "· 쿠폰은 랜덤으로 발송되어 사이렌오더 사용이 불가할 수 있다는 점 참고 부탁드립니다. \n· 스타벅스 정책 상 쿠폰번호가 12자리인 쿠폰만 사이렌오더 적용이 가능합니다.  \n· 1000원 이상 “스타벅스 카드“로 추가 결제시 별 적립이 가능합니다. \n· KT 통신사 멤버십으로 무료 사이즈 UP이 가능합니다. \n· 스타벅스 무료 음료 쿠폰의 경우 품목형 상품으로 매장에서 제조되는 음료(특별, 프로모션 음료 제외)에 적용이 가능합니다. \n· Tall 상품의 경우 사이즈 변경을 원하실 경우 타 상품 교환과 동일한 처리가 되는 점 참고 부탁드립니다. \n· 사이렌 오더 사용 가능 : 카카오 선물하기, 기프티콘, 기프티쇼, 머니콘, 아이넘버, 쓱페이콘, 도넛북 \n· 사이렌 오더 사용 방법 : 스타벅스 앱 접속 > 상품,매장 선택 후 결제페이지 > 선물 > +제휴사 쿠폰 > 바코드 번호 입력 후 적용하기\n 무료음료쿠폰은 앱에서 등록 및 사이렌오더 사용불가(매장 방문 후 바코드 직접 결제만 가능)",
      imageUrl: "https://d1tftw9jjs9bx5.cloudfront.net/cf5c9abb-8f95-43b3-8cab-c2152ce544b7.jpg",
      conCategory1: {
        id: 67,
        name: "카페",
        createdAt: "2017-01-26T07:13:48.000Z",
        priority: 10001,
        discountRate: 0,
        info: "·  품목형은 동일 품목으로만 교환이 가능하며 타 상품 교환,금액권처럼 사용시 사용이 불가하거나 원가금액만큼 제공 받을 수 있는건 아닙니다.\n·  일부 매장, 품목형의 경우 사용이 제한될 수 있으므로 사용 가능 여부는 방문하실 매장에 미리 확인 후 구매 부탁드립니다.\n·  구매하신 상품은 반드시 유효기간 내에 사용해 주셔야 합니다.\n· 포인트 적립 및 제휴카드 할인 등은 교환처의 정책에 따르므로 모바일 쿠폰의 경우 적립, 할인 등이 불가할 수 있습니다.\n·  바코드 인식이 불가할 경우 수기로 입력하여 사용 가능합니다. 또한 사용처의 연동 문제로 키오스크 사용이 불가 할 수 있으므로 매장 직원에게 사용시도 부탁드리겠습니다.\n·  사용처에서 제공하는 웹, 앱 등에 적용이 불가할 수 있으며 쿠폰은 선택하여 구매가 불가하므로 적용 불가 쿠폰일 경우 오프라인 매장에서 사용 시도 부탁드립니다.\n·  프로모션 및 이벤트 상품으로 구매하신 상품의 원가와 영수증에 표기되는 금액이 상이할 수 있습니다.\n· 모바일 쿠폰 중복 사용등은 사용처의 정책이므로 자세한 사항은 방문하실 매장 혹은 사용처 고객센터로 문의 후 구매 권장드립니다.",
        imageUrl: "https://d1dsr05o5i286u.cloudfront.net/a2402a35-038b-4b68-a152-2cc14dff532c.jpg",
      },
    },
  },
  {
    expireAt: "2023-05-10T15:00:00.000Z",
    id: 4014,
    name: "삐꼴라",
    originalPrice: 4500,
    createdAt: "2018-11-13T02:29:38.000Z",
    sfId: "3809850479",
    minSellingPrice: 3660,
    ncSellingPrice: 3700,
    information: null,
    tip: null,
    warning: null,
    discountRate: 19,
    askingPrice: 3410,
    isRefuse: 1,
    isBlock: 0,
    info: null,
    isOnlyAccount: 0,
    conCategory2Id: 352,
    imageUrl: "https://d2lfdrnysfmya6.cloudfront.net/66090450-724e-4f7e-9f8e-3930096a39b0.jpg",
    descriptionImageUrl: null,
    topDescriptionImageUrl: null,
    bottomDescriptionImageUrl: null,
    tutorialImageUrl: null,
    shortcutUrl: null,
    savingRatio: 0,
    isBarcode: true,
    conCategory2: {
      id: 352,
      name: "빨라쪼",
      adminUserId: 24,
      priority: 0,
      createdAt: "2018-11-13T02:15:07.000Z",
      conCategory1Id: 60,
      info: null,
      imageUrl: "https://d1tftw9jjs9bx5.cloudfront.net/c12531c5-0c7b-4248-ba88-79d615db0f5e.jpg",
      conCategory1: {
        id: 60,
        name: "빵,아이스크림",
        createdAt: "2017-01-20T08:45:36.000Z",
        priority: 8001,
        discountRate: 0,
        info: "·  품목형의 상품일 경우 동일 상품으로만 교환가능하며 타 상품 교환,금액권처럼 사용시 원가금액만큼 제공 받을 수 있는건 아닙니다.\n·  쿠폰 사용처에서 유효기간 내 사용이 가능합니다.\n·  포인트 적립 및 제휴카드 할인 등은 교환처의 정책에 따르므로 모바일 쿠폰의 경우 적립,할인 등이 불가 할 수 있습니다.\n·  바코드 인식이 불가 할 경우 수기로 입력하여 사용 가능합니다. 또한 사용처의 연동문제로 키오스크 사용이 불가 할 수 있으므로 매장직원에게 사용시도 부탁 \n    드리겠습니다.\n·  매장에 따라 해당 상품이 품절 및 단종될 경우(ex. 시즌 상품)가 있으므로 방문하실 매장에 재고 확인 후 방문 바랍니다.\n·  본 상품은 매장별 판매가격이 상이 할 수 있으며, 일부매장에서는 추가금액 결제 후 교환 가능합니다.\n·  쿠폰에 명시되어 있는 상품으로만 교환이 가능합니다. (타 제품 교환불가)\n·  금액권일 경우 잔액소멸형 상품으로 해당 금액보다 낮은 상품으로 교환시 잔액이 소멸됩니다.\n·  공항, 백화점, 대형 쇼핑몰, 휴게소 등 일부 매장에서는 사용이 제한될 수 있습니다. 정확한 사용 가능 여부는 방문하실 매장에 확인 후 구매 권장드립니다.\n·  사용처에서 제공하는 웹,앱에 적용이 불가할 수 있으며 쿠폰의 기본 사용은 오프라인 매장이 기준이므로 오프라인 매장에서 사용시도 부탁드리겠습니다.\n· 모바일 쿠폰 중복 사용등은 사용처의 정책이므로 자세한 사항은 방문하실 매장 혹은 사용처 고객센터로 문의 후 구매 권장드립니다.",
        imageUrl: "https://d1dsr05o5i286u.cloudfront.net/bf6a8e6a-d483-47cd-a77b-c74623740eda.jpg",
      },
    },
  },
];

export const menuItemMockData: IConItemDetail = {
  id: 12099,
  name: "e기프트카드 1만원권",
  originalPrice: 10000,
  minSellingPrice: 9650,
  ncSellingPrice: 9650,
  information: null,
  tip: null,
  warning:
    "[환불 규정]\n\n1. 단순 변심 및 구매 실수 등으로 환불 및 교환 원하실 경우에는 7일 이내 가능합니다.\n2. 사용처에서는 잔액 환불이 불가하며, 잔액 환불 시 고객센터로 문의해 주시기 바랍니다.\n3. 1만원 초과 상품권 60% 이상 (1만원 이하 80%) 사용 시 환불 신청 가능합니다.\n4. 잔액 환불은 구매금액을 기준으로 사용 비율에 따라 계산하여 환불됩니다\n    \n    ex) 할인 상품 구매 시, 잔액을 기준으로 할인율 차감 후 환불 처리\n    \n5. 최초 유효기간 만료 전 연장이 가능하며, 3개월 단위로 연장 가능합니다. \n6. 최초 유효기간 경과 시 90% 환불 가능합니다.\n7. 상품권 번호 도난, 분실 등의 고객 부주의로 발생한 사고에 대해서는 보상 불가합니다.",
  discountRate: 4,
  info: "[브랜드소개]\n커피에반하다는 커피문화 대중화를 위해 착한가격과 고품격의 커피맛을 추구하는 국내 토종 브랜드 입니다.\n\n[이용안내]\n1. 본 쿠폰은 해당 제품으로만 교환 가능합니다.(hot & ice 변경 불가능)\n2. 본 상품은 매장 재고 상황에 따라 동일 상품으로 교환이 불가 할 수 있습니다.\n3. 매장에서 해당 제품 구매가 어려운 경우, 다른매장을 이용하시거나 모바일쿠폰 구매처를 통해서 취소/환불할 수 있습니다.\n4. 본 쿠폰 이용 시 포인트(스탬프)적립은 브랜드사 정책에 따릅니다.\n5. 시즌성 상품, 할인 상품의 경우 유효기간이 상이 할 수 있습니다.\n6. 본 쿠폰은 매장 방문 시에만 사용이 가능합니다 (배달앱, 스마트카페, 타 온라인 사용 불가)\n7. 모바일상품권은 현금과 교환 불가합니다.\n8. 구매금액 초과 시 차액을 지급하시면 추가 상품 구매가 가능합니다.",
  isOnlyAccount: 0,
  conCategory2Id: 279,
  imageUrl: "https://d2na9jaypdrp94.cloudfront.net/Y8CbegQmos.png",
  descriptionImageUrl: null,
  topDescriptionImageUrl: null,
  bottomDescriptionImageUrl: null,
  tutorialImageUrl: null,
  shortcutUrl: null,
  descriptionImages: [],
  savingRatio: 0,
  conCategory2: {
    id: 279,
    name: "커피에반하다",
    adminUserId: 19,
    priority: 5000,
    createdAt: "2017-12-04T06:52:03.000Z",
    conCategory1Id: 67,
    info: null,
    imageUrl: "https://d1tftw9jjs9bx5.cloudfront.net/Yv4s6MbTHW.png",
    conCategory1: {
      id: 67,
      name: "카페",
      createdAt: "2017-01-26T07:13:48.000Z",
      priority: 10001,
      discountRate: 0,
      info: "·  품목형은 동일 품목으로만 교환이 가능하며 타 상품 교환,금액권처럼 사용시 사용이 불가하거나 원가금액만큼 제공 받을 수 있는건 아닙니다.\n·  일부 매장, 품목형의 경우 사용이 제한될 수 있으므로 사용 가능 여부는 방문하실 매장에 미리 확인 후 구매 부탁드립니다.\n·  구매하신 상품은 반드시 유효기간 내에 사용해 주셔야 합니다.\n· 포인트 적립 및 제휴카드 할인 등은 교환처의 정책에 따르므로 모바일 쿠폰의 경우 적립, 할인 등이 불가할 수 있습니다.\n·  바코드 인식이 불가할 경우 수기로 입력하여 사용 가능합니다. 또한 사용처의 연동 문제로 키오스크 사용이 불가 할 수 있으므로 매장 직원에게 사용시도 부탁드리겠습니다.\n·  사용처에서 제공하는 웹, 앱 등에 적용이 불가할 수 있으며 쿠폰은 선택하여 구매가 불가하므로 적용 불가 쿠폰일 경우 오프라인 매장에서 사용 시도 부탁드립니다.\n·  프로모션 및 이벤트 상품으로 구매하신 상품의 원가와 영수증에 표기되는 금액이 상이할 수 있습니다.\n· 모바일 쿠폰 중복 사용등은 사용처의 정책이므로 자세한 사항은 방문하실 매장 혹은 사용처 고객센터로 문의 후 구매 권장드립니다.",
      imageUrl: "https://d1dsr05o5i286u.cloudfront.net/a2402a35-038b-4b68-a152-2cc14dff532c.jpg",
    },
  },
  options: [],
};
